def getMessageBoxText():
    return {"close": "<span style=\"font-size: 15px\">Are you sure to quit?</span>",
            "logout": "<span style=\"font-size: 15px\">Are you sure to logout?</span>",
            "about": "<span style=\"font-size: 15px\">"
                         "Messenger **.**.2020<br>"
                         "Version: 1.1"
                     "</span><br><br>"
                         "Created by Vadym Mariiechko",
            "contacts": "<span style=\"font-size: 15px\">"
                            "Vadym Mariiechko:<br>"
                            "LinkedIn: <a href='http<h5>s://www.linkedin.com/in/mariiechko/'>mariiechko</a><br>"
                            "GitHub: <a href='https://github.com/marik348'>marik348</a>"
                        "</span> ",
            "serverIsOff": "<span style=\"font-size: 15px\">The server is offline</span>",
            "commands": "<span style=\"font-size: 14px\"><table>"
                            "<tr>"
                                "<th>Commands&emsp;</th>"
                                "<th>Description</th>"
                            "</tr>"
                            "<tr>"
                                "<td><code>close</code></td>"
                                "<td>Close the messenger</td>"
                            "</tr>"
                            "<tr>"
                                "<td><code>logout</code></td>"
                                "<td>Logout account</td>"
                            "</tr>"
                            "<tr>"
                                "<td><code>reload</code></td>"
                                "<td>Clear commands messages</td>"
                            "</tr>"
                            "<tr>"
                                "<td><code>help</code></td>"
                                "<td>Prints available commands</td>"
                            "</tr>"
                            "<tr>"
                                "<td><code>myself</code></td>"
                                "<td>Prints info about you</td>"
                            "</tr>"
                            "<tr>"
                                "<td><code>status</code></td>"
                                "<td>Prints server statu</td>"
                            "</tr>"
                            "<tr>"
                                "<td><code>online</code></td>"
                                "<td>Prints online userst</td>"
                            "</tr>"
                            "<tr>"
                                "<td><code>reg</code></td>"
                                "<td>Prints registered users/td>"
                            "</tr>"
                        "</table></span>",
            "shortcuts": "<span style=\"font-size: 15px\"> </span>"
            }
